import type { Metadata } from 'next';
import type React from 'react';

export const metadata: Metadata = {
  title: 'Koalaty Speech and Feeding',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
